### ISSUE TITLE
getting an error after inputing the destination

### ISSUE THREAD

**Issue by samueltuyizere** [Jodagito/YouTubeDownloader#1]
/Users/sam/Desktop/YouTubeDownloader/yenv/bin/python3: Error while finding module specification for 'YouTubeDownloader.py' (ModuleNotFoundError: __path__ attribute not found on 'YouTubeDownloader' while trying to find 'YouTubeDownloader.py')

**Comment by Jodagito** [comment]
Sorry for the delay. How are you exactly executing this module?

If you're doing it by calling python -m YouTubeDownloader.py then you should remove .py suffix on it, so it should look like this, python -m YouTubeDownloader

Anyway this isn't a module problem so I'll close this.
